/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as CollectionsIndexRouteImport } from './routes/collections/index';
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index';
import { Route as CheckoutResultRouteImport } from './routes/checkout/result';
import { Route as ProductsSlugRouteImport } from './routes/products/$slug';
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any);
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any);
const CheckoutResultRoute = CheckoutResultRouteImport.update({
  id: '/checkout/result',
  path: '/checkout/result',
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any);
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/collections/$slug': typeof CollectionsSlugRoute;
  '/products/$slug': typeof ProductsSlugRoute;
  '/checkout/result': typeof CheckoutResultRoute;
  '/checkout/': typeof CheckoutIndexRoute;
  '/collections/': typeof CollectionsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/collections/$slug': typeof CollectionsSlugRoute;
  '/products/$slug': typeof ProductsSlugRoute;
  '/checkout/result': typeof CheckoutResultRoute;
  '/checkout': typeof CheckoutIndexRoute;
  '/collections': typeof CollectionsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/collections/$slug': typeof CollectionsSlugRoute;
  '/products/$slug': typeof ProductsSlugRoute;
  '/checkout/result': typeof CheckoutResultRoute;
  '/checkout/': typeof CheckoutIndexRoute;
  '/collections/': typeof CollectionsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/collections/$slug'
    | '/products/$slug'
    | '/checkout/result'
    | '/checkout/'
    | '/collections/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/collections/$slug'
    | '/products/$slug'
    | '/checkout/result'
    | '/checkout'
    | '/collections';
  id:
    | '__root__'
    | '/'
    | '/collections/$slug'
    | '/products/$slug'
    | '/checkout/result'
    | '/checkout/'
    | '/collections/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CollectionsSlugRoute: typeof CollectionsSlugRoute;
  ProductsSlugRoute: typeof ProductsSlugRoute;
  CheckoutResultRoute: typeof CheckoutResultRoute;
  CheckoutIndexRoute: typeof CheckoutIndexRoute;
  CollectionsIndexRoute: typeof CollectionsIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/collections/': {
      id: '/collections/';
      path: '/collections';
      fullPath: '/collections/';
      preLoaderRoute: typeof CollectionsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/checkout/': {
      id: '/checkout/';
      path: '/checkout';
      fullPath: '/checkout/';
      preLoaderRoute: typeof CheckoutIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/checkout/result': {
      id: '/checkout/result';
      path: '/checkout/result';
      fullPath: '/checkout/result';
      preLoaderRoute: typeof CheckoutResultRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/products/$slug': {
      id: '/products/$slug';
      path: '/products/$slug';
      fullPath: '/products/$slug';
      preLoaderRoute: typeof ProductsSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/collections/$slug': {
      id: '/collections/$slug';
      path: '/collections/$slug';
      fullPath: '/collections/$slug';
      preLoaderRoute: typeof CollectionsSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CheckoutResultRoute: CheckoutResultRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
