# Generated by Django 5.0.8 on 2025-10-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_src',
            field=models.URLField(blank=True, help_text='Category image URL', null=True),
        ),
        migrations.AddField(
            model_name='occasion',
            name='image_src',
            field=models.URLField(blank=True, help_text='Occasion image URL', null=True),
        ),
    ]
