# Generated by Django 5.0.8 on 2025-11-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_src_occasion_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_src',
            field=models.URLField(blank=True, help_text='Category image URL', null=True),
        ),
    ]
