# Generated by Django 5.0.8 on 2026-01-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_collection_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=list, help_text='Array of variant objects with id, name, and main_image'),
        ),
    ]
