# Generated by Django 5.0.8 on 2026-01-15 20:48

from django.db import migrations


def populate_variants(apps, schema_editor):
    """
    Populate the variants field for all products based on their base_name.
    Groups products by base_name and creates variant objects for each group.
    """
    Product = apps.get_model('products', 'Product')

    # Get all products ordered by base_name to group them
    all_products = Product.objects.all().order_by('base_name', 'id')

    # Group products by base_name
    variant_groups = {}
    for product in all_products:
        base_name = product.base_name or product.name
        if base_name not in variant_groups:
            variant_groups[base_name] = []
        variant_groups[base_name].append(product)

    # For each product, create its variants array
    for product in all_products:
        base_name = product.base_name or product.name
        variants = []

        # Add all products with the same base_name as variants
        for variant_product in variant_groups[base_name]:
            # Determine display name based on variant_type
            variant_type = variant_product.variant_type
            if variant_type == 'single':
                display_name = 'Single'
            elif variant_type == 'double':
                display_name = 'Double'
            elif variant_type == 'triple':
                display_name = 'Triple'
            else:
                display_name = 'Standard'

            variants.append({
                'id': variant_product.id,
                'name': display_name,
                'main_image': variant_product.main_image
            })

        # Sort variants by id to ensure consistent ordering
        variants.sort(key=lambda v: v['id'])

        # Update the product with its variants
        product.variants = variants
        product.save(update_fields=['variants'])


def reverse_populate_variants(apps, schema_editor):
    """
    Clear the variants field when rolling back the migration.
    """
    Product = apps.get_model('products', 'Product')
    Product.objects.all().update(variants=[])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_variants'),
    ]

    operations = [
        migrations.RunPython(populate_variants, reverse_populate_variants),
    ]
