# Generated by Django 5.0.8 on 2026-02-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_fix_variant_type_casing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blur_data_url',
            field=models.TextField(blank=True, help_text='Base64 encoded low-res blur placeholder', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=list, help_text='Array of variant objects with id, name, variant_type, main_image, hover_image, delivery_lead_time, badge_text, price_dollars, and discounted_price_dollars'),
        ),
    ]
