# Generated by Django 5.0.8 on 2026-03-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_position_to_junction_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nav_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='nav_img_src',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='nav_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='nav_img_src',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occasion',
            name='nav_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occasion',
            name='nav_img_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
