# Generated by Django 5.0.8 on 2026-04-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_color_stemtype_productcolor_productstemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vase_included',
            field=models.BooleanField(default=False, help_text='Product comes with a vase/vessel (derived from text at seed time)'),
        ),
    ]
