# Generated by Django 5.0.8 on 2026-05-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_vase_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_src',
            field=models.URLField(blank=True, help_text='Image URL', null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image_src',
            field=models.URLField(blank=True, help_text='Image URL', null=True),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='image_src',
            field=models.URLField(blank=True, help_text='Image URL', null=True),
        ),
    ]
