# Generated by Django 5.0.8 on 2026-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_image_src_alter_collection_image_src_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', through='products.ProductCategory', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(related_name='products', through='products.ProductCollection', to='products.collection'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='products', through='products.ProductColor', to='products.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasions',
            field=models.ManyToManyField(related_name='products', through='products.ProductOccasion', to='products.occasion'),
        ),
        migrations.AddField(
            model_name='product',
            name='stem_types',
            field=models.ManyToManyField(related_name='products', through='products.ProductStemType', to='products.stemtype'),
        ),
    ]
