# Generated by Django 5.0.8 on 2026-05-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_categories_product_collections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
    ]
