# Generated by Django 5.0.8 on 2026-05-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_variants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
