# Generated by Django 5.0.8 on 2026-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, choices=[('New!', 'New!'), ('Sale', 'Sale'), ('Best Seller', 'Best Seller'), ('Limited Time Sale: 20% Off', 'Limited Time Sale: 20% Off')], max_length=30, null=True),
        ),
    ]
