# Generated by Django 5.0.8 on 2026-05-06 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_badge_text_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="e.g. 'category', 'color'", unique=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Category', 'Color'", max_length=50)),
                ('kind', models.CharField(choices=[('landing', 'Landing'), ('filter', 'Filter')], help_text='`landing` = facet whose tags have their own page (cat/col/occ); `filter` = filter-only facet (color, stem_type)', max_length=20)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image_src', models.URLField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('header_title', models.CharField(blank=True, max_length=500, null=True)),
                ('header_subtitle', models.TextField(blank=True, null=True)),
                ('nav_img_src', models.URLField(blank=True, null=True)),
                ('nav_description', models.TextField(blank=True, null=True)),
                ('hex', models.CharField(blank=True, help_text='Hex color code, e.g. #C97B8E', max_length=7, null=True)),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='products.facet')),
            ],
            options={
                'ordering': ['facet', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display position within this tag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.tag')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', through='products.ProductTag', to='products.tag'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='products_ta_slug_d1be68_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('facet', 'slug'), name='unique_tag_per_facet'),
        ),
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together={('product', 'tag')},
        ),
    ]
