# Generated by Django 5.0.8 on 2026-05-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_drop_legacy_facets'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addon_type',
            field=models.CharField(blank=True, choices=[('vase', 'Vase'), ('gift', 'Gift')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, choices=[('New!', 'New!'), ('Sale', 'Sale'), ('Best Seller', 'Best Seller')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
