"""
Django settings for urbanstems_backend project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-$blv$w)g*(s_84!_f#el6d#tjw6h&k#2zgf#l%zl3w^6!g2%0+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'products',
    'places',
    'checkout',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urbanstems_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'urbanstems_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres:postgres@db:5432/urbanstems',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'products.pagination.CustomPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    # Rate limits below are per client IP. They protect the (billable)
    # Google Places endpoints from being drained by a single client.
    'DEFAULT_THROTTLE_RATES': {
        'places-autocomplete': '30/min',
        'places-details': '20/min',
        'places-detect': '10/min',
    },
}

# CORS settings (for frontend development)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

CORS_ALLOW_CREDENTIALS = True

# Number of trusted proxy hops between the public internet and Django. Used
# by rate-limiting and IP geolocation to identify the real client IP from
# X-Forwarded-For. 0 = no proxy (use REMOTE_ADDR). 1 = single proxy (Railway,
# nginx). See docs/places-and-geo.md "Railway deployment" for details.
TRUSTED_PROXY_HOPS = config('TRUSTED_PROXY_HOPS', default=0, cast=int)

# Cache backend. Redis is required as soon as Django runs in more than one
# process (multiple workers, multiple containers): without it, throttle
# counters and response cache are per-process, halving rate-limit accuracy
# and the cache hit ratio. Falls back to LocMem when REDIS_URL is unset.
_REDIS_URL = config('REDIS_URL', default='')
if _REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _REDIS_URL,
        }
    }

# Path to the MaxMind GeoLite2 City database. Downloaded from MaxMind (free
# account) and dropped at the default path below; the geo-detect endpoint
# returns a fallback location when the file is missing.
GEOIP_DB_PATH = config(
    'GEOIP_DB_PATH',
    default=str(BASE_DIR / 'data' / 'geoip' / 'GeoLite2-City.mmdb'),
)

# Default coords used when client IP is private/loopback (e.g. local dev) or
# when the GeoIP DB is missing. Picked to bias autocomplete sensibly out of
# the box.
GEOIP_FALLBACK_LAT = config('GEOIP_FALLBACK_LAT', default=40.7128, cast=float)
GEOIP_FALLBACK_LNG = config('GEOIP_FALLBACK_LNG', default=-74.006, cast=float)

# Stripe. Test-mode keys (sk_test_..., pk_test_...) are fine for the sim;
# the publishable key is consumed by the frontend via VITE_STRIPE_PUBLISHABLE_KEY.
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_CURRENCY = config('STRIPE_CURRENCY', default='usd')
# Webhook signing secret. Different per environment: Railway dashboard's
# webhook gives one, the local `stripe listen` CLI prints another. Set to
# the matching one wherever the server runs.
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# Resend. Free tier (3k/month, 100/day) is plenty for the sim.
RESEND_API_KEY = config('RESEND_API_KEY', default='')
# Sender address. Must be a verified domain in Resend, or the sandbox
# `onboarding@resend.dev` (which only delivers to your signup email).
EMAIL_FROM = config(
    'EMAIL_FROM',
    default='UrbanStems <onboarding@resend.dev>',
)
# Logo for the order confirmation email. Must be a PNG/JPEG hosted at a
# public URL (Gmail strips inline data: URIs and most clients don't render
# SVG). Default points at a public LinkedIn-hosted UrbanStems logo as a
# placeholder; swap to a self-hosted asset when convenient.
EMAIL_LOGO_URL = config(
    'EMAIL_LOGO_URL',
    default='https://media.licdn.com/dms/image/v2/C4E0BAQE30cC9hM4k9A/company-logo_200_200/company-logo_200_200/0/1630593771861/urbanstems_logo?e=2147483647&v=beta&t=z4q6y0lLO8f_W8pfs9qim9FYppDUxj9gW7J7A5NL2YQ',
)
# Store URL used for the "Continue Shopping" CTA in the email. Defaults to
# the production frontend.
STORE_URL = config(
    'STORE_URL', default='https://urbanstems.francescoseddo.me'
)
# Sales tax percentage applied to the order subtotal in the PaymentIntent.
# 8.875 matches NYC combined sales tax — easy to swap for a real lookup later.
CHECKOUT_TAX_RATE_PCT = config('CHECKOUT_TAX_RATE_PCT', default=8.875, cast=float)
# Free shipping kicks in at this subtotal; mirrors FREE_SHIPPING_THRESHOLD on
# the frontend cart pane.
CHECKOUT_FREE_SHIPPING_THRESHOLD_CENTS = config(
    'CHECKOUT_FREE_SHIPPING_THRESHOLD_CENTS', default=14000, cast=int
)
CHECKOUT_FLAT_SHIPPING_CENTS = config(
    'CHECKOUT_FLAT_SHIPPING_CENTS', default=1500, cast=int
)
